# This is a basic workflow to help you get started with Actions

name: Algolia crawler for stage

on:
 workflow_dispatch:
     inputs:
      environment:
        description: 'Environment you want to run'
        required: true
        default: 'https://staging.lambdatestinternal.com'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: stage
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: 'Create env file'
        run: |
          touch .env
          echo "APPLICATION_ID=${{ secrets.APPLICATION_ID }}" >> .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          
      - name: Run algolia crawler on stage website
        run: |
             cat algolia_config.json
             docker run -i --env-file=.env -e "CONFIG=$(cat algolia_config.json | jq -r tostring)" algolia/docsearch-scraper

